[colors]
foreground = "#8b93a2"
background = "#1f2229"
cursor_bg = "#528bff"
cursor_fg = "#ffffff"
cursor_border = "#528bff"
selection_fg = "#1f2229"
selection_bg = "#61afef"
scrollbar_thumb = "#4b5263"
split = "#3e4451"

ansi = [
  "#1f2229", # black
  "#e06c75", # red
  "#8dc891", # green
  "#e5c07b", # yellow
  "#61afef", # blue
  "#c678dd", # magenta
  "#56b6c2", # cyan
  "#8b93a2", # white
]

brights = [
  "#5c6370", # bright black
  "#e06c75", # bright red
  "#8dc891", # bright green
  "#e5c07b", # bright yellow
  "#61afef", # bright blue
  "#c678dd", # bright magenta
  "#56b6c2", # bright cyan
  "#ffffff", # bright white
]

[colors.tab_bar]
background = "#191c21"

  [colors.tab_bar.active_tab]
  bg_color = "#1f2229"
  fg_color = "#e5c07b"
  intensity = "Bold"

  [colors.tab_bar.inactive_tab]
  bg_color = "#191c21"
  fg_color = "#5c6370"

  [colors.tab_bar.inactive_tab_hover]
  bg_color = "#1f2229"
  fg_color = "#e5c07b"
  italic = true

  [colors.tab_bar.new_tab]
  bg_color = "#191c21"
  fg_color = "#5c6370"

  [colors.tab_bar.new_tab_hover]
  bg_color = "#1f2229"
  fg_color = "#e5c07b"
  italic = true
