[colors]
foreground = "#a0a8b7"
background = "#1f2329"
cursor_bg = "#528bff"
cursor_fg = "#ffffff"
cursor_border = "#528bff"
selection_fg = "#1e2127"
selection_bg = "#61afef"
scrollbar_thumb = "#4b5263"
split = "#3e4451"

ansi = [
    "#0e1013", # black
    "#e55561", # red
    "#8ebd6b", # green
    "#e2b86b", # yellow
    "#4fa6ed", # blue
    "#bf68d9", # magenta
    "#48b0bd", # cyan
    "#a0a8b7", # white
]

brights = [
    "#535965", # grey
    "#e55561", # red
    "#8ebd6b", # green
    "#e2b86b", # yellow
    "#4fa6ed", # blue
    "#bf68d9", # magenta
    "#48b0bd", # cyan
    "#a0a8b7", # white
    # "#5c6370", # bright black
    # "#e06c75", # bright red
    # "#98c379", # bright green
    # "#e5c07b", # bright yellow
    # "#61afef", # bright blue
    # "#c678dd", # bright magenta
    # "#56b6c2", # bright cyan
    # "#ffffff", # bright white
]

[colors.tab_bar]
background = "#181a1f"

  [colors.tab_bar.active_tab]
bg_color = "#1e2127"
fg_color = "#e5c07b"
intensity = "Bold"

  [colors.tab_bar.inactive_tab]
bg_color = "#181a1f"
fg_color = "#5c6370"

  [colors.tab_bar.inactive_tab_hover]
bg_color = "#1e2127"
fg_color = "#e5c07b"
italic = true

  [colors.tab_bar.new_tab]
bg_color = "#181a1f"
fg_color = "#5c6370"

  [colors.tab_bar.new_tab_hover]
bg_color = "#1e2127"
fg_color = "#e5c07b"
italic = true
