[colors]
foreground = "#abb2bf"
background = "#282c34"
cursor_bg = "#528bff"
cursor_fg = "#ffffff"
cursor_border = "#528bff"
selection_fg = "#282c34"
selection_bg = "#61afef"
scrollbar_thumb = "#4b5263"
split = "#3e4451"

ansi = [
  "#282c34", # black
  "#e06c75", # red
  "#98c379", # green
  "#e5c07b", # yellow
  "#61afef", # blue
  "#c678dd", # magenta
  "#56b6c2", # cyan
  "#dcdfe4", # white
]

brights = [
  "#5c6370", # bright black
  "#e06c75", # bright red
  "#98c379", # bright green
  "#e5c07b", # bright yellow
  "#61afef", # bright blue
  "#c678dd", # bright magenta
  "#56b6c2", # bright cyan
  "#ffffff", # bright white
]

[colors.tab_bar]
background = "#21252b"

  [colors.tab_bar.active_tab]
  bg_color = "#282c34"
  fg_color = "#e5c07b"
  intensity = "Bold"

  [colors.tab_bar.inactive_tab]
  bg_color = "#21252b"
  fg_color = "#5c6370"

  [colors.tab_bar.inactive_tab_hover]
  bg_color = "#282c34"
  fg_color = "#e5c07b"
  italic = true

  [colors.tab_bar.new_tab]
  bg_color = "#21252b"
  fg_color = "#5c6370"

  [colors.tab_bar.new_tab_hover]
  bg_color = "#282c34"
  fg_color = "#e5c07b"
  italic = true
