[colors]
foreground = "#c6bdb4"
background = "#282c34"
cursor_bg = "#e06c75"
cursor_fg = "#282c34"
cursor_border = "#e06c75"
selection_fg = "#282c34"
selection_bg = "#e06c75"
scrollbar_thumb = "#4b5263"
split = "#3e4451"

ansi = [
  "#282c34", # black
  "#e06c75", # red
  "#e5c07b", # green
  "#d19a66", # yellow
  "#61afef", # blue
  "#c678dd", # magenta
  "#d19a66", # cyan
  "#c6bdb4", # white
]

brights = [
  "#5c6370", # bright black
  "#e06c75", # bright red
  "#e5c07b", # bright green
  "#d19a66", # bright yellow
  "#61afef", # bright blue
  "#c678dd", # bright magenta
  "#d19a66", # bright cyan
  "#ffffff", # bright white
]

[colors.tab_bar]
background = "#21252b"

  [colors.tab_bar.active_tab]
  bg_color = "#282c34"
  fg_color = "#e06c75"
  intensity = "Bold"

  [colors.tab_bar.inactive_tab]
  bg_color = "#21252b"
  fg_color = "#5c6370"

  [colors.tab_bar.inactive_tab_hover]
  bg_color = "#282c34"
  fg_color = "#e06c75"
  italic = true

  [colors.tab_bar.new_tab]
  bg_color = "#21252b"
  fg_color = "#5c6370"

  [colors.tab_bar.new_tab_hover]
  bg_color = "#282c34"
  fg_color = "#e06c75"
  italic = true
